#:schema node_modules/wrangler/config-schema.json
name = "webpage-scrapper"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

observability = { enabled = true }

browser = { binding = "SCRAPPER_BROWSER" }

d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata-dev", database_id = "56f92781-5084-4333-a331-9cfdfaa0710f" }
]
r2_buckets = [
	{ binding = "RAW_HTML_BUCKET", bucket_name = "web-rag-composer-raw-html-dev" }
]

[env.production]
d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata", database_id = "9deb74a3-287b-4d8b-a020-6662cfbd9a01" }
]
r2_buckets = [
	{ binding = "RAW_HTML_BUCKET", bucket_name = "web-rag-composer-raw-html" }
]