-- SQLITE 
DROP TABLE IF EXISTS PageMetadata;
DROP INDEX IF EXISTS idx_url;

CREATE TABLE IF NOT EXISTS PageMetadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL UNIQUE,
    r2_path TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_url ON PageMetadata (url, r2_path);